# Generated by Django 4.2 on 2024-10-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_handle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_type',
            field=models.CharField(choices=[('Genaral_user', 'General User'), ('Teacher', 'Teacher'), ('Student', 'Student')], default='General User', max_length=30),
        ),
    ]
