# Generated by Django 4.2 on 2024-09-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('EDU', 'Education'), ('ENT', 'Entertainment'), ('TECH', 'Technology'), ('LIFE', 'Lifestyle'), ('SPORT', 'Sports'), ('MUSIC', 'Music'), ('NEWS', 'News')], max_length=10)),
                ('link', models.URLField(max_length=250)),
                ('thumbnail', models.URLField(max_length=250)),
            ],
        ),
    ]
